### ISSUE TITLE
Refactor to securely handle service credentials

### ISSUE THREAD

**Issue by Shalsh23** [NCEAS/osti-elink#1]
**Is your feature request related to a problem? Please describe.**
Currently, the `test.properties` file within the repository contains hardcoded service credentials (username and password). This practice poses a security risk as it can expose sensitive information. To enhance the security of the application and adhere to best practices, refactoring of the credential management process is required.

**Describe the solution you'd like.**
Utilize external configuration files or environment variables to securely manage credentials.

**Comment by taojing2002** [comment]
In the test.properties, the properties looks like:
```
ostiService.passwordFilePath=./password.properties
```
The password.properties file should look like:
```
guid.doi.username=your-username                                                                                                 
guid.doi.password=your-password
```
